package com.amapolazul.www.wordplay.peristencia;

import com.amapolazul.www.wordplay.R;

/**
 * Created by jsmartinez on 12/12/2015.
 */
public class DatabaseStartup {

    public static int[] darImagenesId(){
        return new int[]{
                R.drawable.p01,
                R.drawable.p02,
                R.drawable.p03,
                R.drawable.p04,
                R.drawable.p05,
                R.drawable.p06,
                R.drawable.p07,
                R.drawable.p08,
                R.drawable.p09,
                R.drawable.p10,
                R.drawable.p11,
                R.drawable.p12,
                R.drawable.p13,
                R.drawable.p14,
                R.drawable.p15,
                R.drawable.p16,
                R.drawable.p17,
                R.drawable.p18,
                R.drawable.p19,
                R.drawable.p20,
                R.drawable.p21,
                R.drawable.p22,
                R.drawable.p23,
                R.drawable.p24,
                R.drawable.p25,
                R.drawable.p26,
                R.drawable.p27,
                R.drawable.p28,
                R.drawable.p29,
                R.drawable.p30,
                R.drawable.p31,
                R.drawable.p32,
                R.drawable.p33,
                R.drawable.p34,
                R.drawable.p35,
                R.drawable.p36,
                R.drawable.p37,
                R.drawable.p38,
                R.drawable.p39,
                R.drawable.p40,
        };
    }

    public static int[] darPopupsId(){
        return new int[]{
                R.drawable.pop1,
                R.drawable.pop2,
                R.drawable.pop3,
                R.drawable.pop4,
                R.drawable.pop5,
                R.drawable.pop6,
                R.drawable.pop7,
                R.drawable.pop8,
                R.drawable.pop9,
                R.drawable.pop10,
                R.drawable.pop11,
                R.drawable.pop12,
                R.drawable.pop13,
                R.drawable.pop14,
                R.drawable.pop15,
                R.drawable.pop16,
                R.drawable.pop17,
                R.drawable.pop18,
                R.drawable.pop19,
                R.drawable.pop20,
                R.drawable.pop21,
                R.drawable.pop22,
                R.drawable.pop23,
                R.drawable.pop24,
                R.drawable.pop25,
                R.drawable.pop26,
                R.drawable.pop27,
                R.drawable.pop28,
                R.drawable.pop29,
                R.drawable.pop30,
                R.drawable.pop31,
                R.drawable.pop32,
                R.drawable.pop33,
                R.drawable.pop34,
                R.drawable.pop35,
                R.drawable.pop36,
                R.drawable.pop37,
                R.drawable.pop38,
                R.drawable.pop39,
                R.drawable.pop40,

        };
    }

    public static String[] palabrasRespuestas() {
        return new String[] {
                "WILLIAM",
                "ANTOINE",
                "GABRIEL",
                "COELHO",
                "ITURRALDE",
                "DANTE",
                "HOMERO",
                "SHAKESPEARE",
                "MARKUS",
                "MARQUEZ",
                "CERVANTES",
                "BARRIE",
                "MARK",
                "WILLIAM",
                "STOKER",
                "FRANCO",
                "DALI",
                "JONATHAN",
                "PATRICK",
                "REUEL",
                "LORCA",
                "NERUDA",
                "GABRIEL",
                "COLLINS",
                "HESSE",
                "SHAKESPEARE",
                "FACIOLINCE",
                "MELLO",
                "GREEN",
                "GARCIA",
                "SAVATER",
                "VICTOR",
                "EDUARDO",
                "ROWLING",
                "JORGE",
                "DUMONT",
                "GAMBOA",
                "WILLIAM",
                "MARQUEZ",
                "MADRID"
        };
    }
}
